//
// TCKeyCode.h
// This file will define the various keycodes supported by the engine.
//

#ifndef __TC_KEY_CODE_H__
#define __TC_KEY_CODE_H__

enum TCKeyCode
{
	TCKeyCode_A = 'A',
	TCKeyCode_B = 'B',
	TCKeyCode_C = 'C',
	TCKeyCode_D = 'D', 
	TCKeyCode_E = 'E',
	TCKeyCode_F = 'F',
	TCKeyCode_G = 'G',
	TCKeyCode_H = 'H',
	TCKeyCode_I = 'I',
	TCKeyCode_J = 'J',
	TCKeyCode_K = 'K',
	TCKeyCode_L = 'L',
	TCKeyCode_M = 'M',
	TCKeyCode_N = 'N',
	TCKeyCode_O = 'O',
	TCKeyCode_P = 'P',
	TCKeyCode_Q = 'Q',
	TCKeyCode_R = 'R',
	TCKeyCode_S = 'S',
	TCKeyCode_T = 'T',
	TCKeyCode_U = 'U',
	TCKeyCode_V = 'V',
	TCKeyCode_W = 'W',
	TCKeyCode_X = 'X',
	TCKeyCode_Y = 'Y',
	TCKeyCode_Z = 'Z',
	TCKeyCode_0 = '0',
	TCKeyCode_1 = '1',
	TCKeyCode_2 = '2',
	TCKeyCode_3 = '3',
	TCKeyCode_4 = '4',
	TCKeyCode_5 = '5',
	TCKeyCode_6 = '6',
	TCKeyCode_7 = '7',
	TCKeyCode_8 = '8',
	TCKeyCode_9 = '9',
	TCKeyCode_Numeric_0 = 96,
	TCKeyCode_Numeric_1,
	TCKeyCode_Numeric_2,
	TCKeyCode_Numeric_3,
	TCKeyCode_Numeric_4,
	TCKeyCode_Numeric_5,
	TCKeyCode_Numeric_6,
	TCKeyCode_Numeric_7,
	TCKeyCode_Numeric_8,
	TCKeyCode_Numeric_9,
	TCKeyCode_Numeric_Multiply,
	TCKeyCode_Numeric_Add,
	TCKeyCode_Numeric_Enter,
	TCKeyCode_Numeric_Subtract,
	TCKeyCode_Numeric_Decimal,
	TCKeyCode_Numeric_Divide,
	TCKeyCode_F1 = 112,
	TCKeyCode_F2,
	TCKeyCode_F3,
	TCKeyCode_F4,
	TCKeyCode_F5,
	TCKeyCode_F6,
	TCKeyCode_F7,
	TCKeyCode_F8,
	TCKeyCode_F9,
	TCKeyCode_F10,
	TCKeyCode_F11,
	TCKeyCode_F12,
	TCKeyCode_F13,
	TCKeyCode_F14,
	TCKeyCode_F15,
	TCKeyCode_Backspace = 8,
	TCKeyCode_Tab,
	TCKeyCode_Enter = 13,
	TCKeyCode_Shift = 16,
	TCKeyCode_Control = 17,
	TCKeyCode_CapsLock = 20,
	TCKeyCode_Escape = 27,
	TCKeyCode_Spacebar = 32,
	TCKeyCode_PageUp,
	TCKeyCode_PageDown,
	TCKeyCode_End,
	TCKeyCode_Home,
	TCKeyCode_LeftArrow,
	TCKeyCode_UpArrow,
	TCKeyCode_RightArrow,
	TCKeyCode_DownArrow,
	TCKeyCode_Insert = 45,
	TCKeyCode_Delete,
	TCKeyCode_NumLock = 144,
	TCKeyCode_ScrollLock,
	TCKeyCode_Pause_Break = 19,
	TCKeyCode_Semicolon = 186,
	TCKeyCode_Equal = 187,
	TCKeyCode_Minus = 189,
	TCKeyCode_ForwardSlash = 191,
	TCKeyCode_BackQuote = 192,
	TCKeyCode_LeftBrace = 219,
	TCKeyCode_Backslash = 220,
	TCKeyCode_RightBrace = 221,
	TCKeyCode_QuotationMark = 222,
	TCKeyCode_Comma = 188,
	TCKeyCode_Period = 190,
};

#endif